### ISSUE TITLE
Downloads TTF files instead of WOFF/WOFF2

### ISSUE THREAD

**Issue by aristath** [matiasbenedetto/google-fonts-to-wordpress-collection#1]
This was brought up in the Gutenberg repo (see https://github.com/WordPress/gutenberg/issues/55049 and https://github.com/WordPress/gutenberg/pull/57706), as well as WP's Slack.
Currently we're downloading `.ttf` files which are quite large and don't support all features that modern font-families have.
We should instead download `.woff` files, or - ideally - `.woff2`.
We should be able to do that by passing a user-agent in the `fetch` call on https://github.com/WordPress/google-fonts-to-wordpress-collection/blob/abe0da82028cbd99bfcf8577cd8a88e8c863f7d4/src/get_google_fonts.js#L80

User-agents we can use:
If we want to get `woff` files, then the one below is the recommended user-agent since it's the only one that also supports unicode-ranges
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
```

If we want to get `woff2` files, then this one will do:
```
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0
```

cc @matiasbenedetto

**Comment by luminuu** [comment]
An alternative approach would be using the `capability` parameter with `WOFF2` as value, as per the Google Fonts documentation: https://developers.google.com/fonts/docs/developer_api#api_url_specification

**Comment by swissspidy** [comment]
Yes this really should use the `capability` parameter where possible, no user agent wizardry

**Comment by aristath** [comment]
Even better 👍

**Comment by matiasbenedetto** [comment]
> An alternative approach would be using the capability parameter with WOFF2 as value, as per the Google Fonts documentation: https://developers.google.com/fonts/docs/developer_api#api_url_specification

This option seems to be new in the Google Fonts API. It didn't exist (or at least I didn't notice it) a few months ago while creating this repo. Good to know that now we have this option available. I think switching from ttf to woff2 should be simple now.

**Comment by aristath** [comment]
> This option seems to be new in the Google Fonts API. It didn't exist (or at least I didn't notice it) a few months ago while creating this repo.

Oh it's definitely new... that's why I initially suggested using the user-agent, we've been using that method for years 'cause until recently there was no other way to do it 😅
